# LinearRegression from Scratch


# 구현할 것
- 공부시간과 성적간의 관계를 모델링한다.
    - **머신러닝 모델(모형)이란** 수집한 데이터를 기반으로 입력값(Feature)와 출력값(Target)간의 관계를 하나의 공식으로 정의한 함수이다. 그 공식을 찾는 과정을 **모델링**이라고 한다.
    - 이 예제에서는 공부한 시험시간으로 점수를 예측하는 모델을 정의한다.
    - 입력값과 출력값 간의 관계를 정의할 수있는 다양한 함수(공식)이 있다. 여기에서는 딥러닝과 관계가 있는 **Linear Regression** 을 사용해본다.

# 데이터 확인
- 입력데이터: 공부시간
- 출력데이터: 성적

|공부시간|점수|
|-|-|
|1|20|
|2|40|
|3|60|

우리가 수집한 공부시간과 점수 데이터를 바탕으로 둘 간의 관계를 식으로 정의 할 수 있으면 **내가 몇시간 공부하면 점수를 얼마 받을 수 있는지 예측할 수 있게 된다.**   
수집한 데이터를 기반으로 앞으로 예측할 수있는 모형을 만드는 것이 머신러닝 모델링이다.

  

## 학습(훈련) 데이터셋 만들기
- 모델을 학습시키기 위한 데이터셋을 구성한다.
- 입력데이터와 출력데이터을 각각 다른 행렬로 구성한다.
- 하나의 데이터 포인트의 입력/출력 값은 같은 index에 정의한다.

### 선형회귀 (Linear Regression)
- Feature들의 가중합을 이용해 Target을 추정한다.
- Feature에 곱해지는 가중치(weight)들은 각 Feature가 Target 얼마나 영향을 주는지 영향도가 된다.
    - 음수일 경우는 target값을 줄이고 양수일 경우는 target값을 늘린다.
    - 가중치가 0에 가까울 수록 target에 영향을 주지 않는 feature이고 0에서 멀수록 target에 많은 영향을 준다.
- 모델 학습과정에서 가장 적절한 Feature의 가중치를 찾아야 한다.
      

\begin{align}
&\large \hat{y} = W\cdot X + b\\
&\small \hat{y}: \text{모델추정값}\\
&\small W: \text{가중치}\\
&\small X: \text{Feature(입력값)}\\
&\small b: \text{bias(편향)}
\end{align}



## Train dataset 구성
- Train data는 feature(input)와 target(output) 각각 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다. 이 문제에서는 `공부시간` 1개의 변수를 가진다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 구성한다.   
  이 문제에서 예측할 항목은 `시험점수` 한개이다.

In [2]:
import torch

X_train = torch.tensor([[1], [2], [3]], dtype=torch.float32)          # 공부시간
y_train = torch.tensor([[20], [40], [60]], dtype=torch.float32)       # 시험점수
X_train.size(), y_train.size()

(torch.Size([3, 1]), torch.Size([3, 1]))

## 파라미터 (weight, bias) 정의
- 학습대상/최적화 대상

In [4]:
weight = torch.randn(1, 1, requires_grad=True)      # feature에 곱할 값(가중치)
# (1: 입력 feature개수, 1: 출력값(예측)의 개수)
bias = torch.randn(1, requires_grad=True)       # bias 값
print(weight.size(), bias.size())
print(weight)
print(bias)

# 정규분포에 따라서 weight, bias를 랜덤반영후, 바꿔나간다.

torch.Size([1, 1]) torch.Size([1])
tensor([[-0.5216]], requires_grad=True)
tensor([0.2398], requires_grad=True)


In [5]:
# 추론
pred = X_train @ weight + bias

In [6]:
# 정답
y_train

tensor([[20.],
        [40.],
        [60.]])

In [7]:
# 오차계산
loss = torch.mean((y_train - pred)**2, dim=0)
loss.backward()
loss

tensor([1945.6740], grad_fn=<MeanBackward1>)

In [ ]:
# gradient계산 -> loss에 대한 weight, bias의 순간변화율(gradient)를 계산

In [8]:
weight.grad, bias.grad

(tensor([[-190.5757]]), tensor([-81.6068]))

In [9]:
lr = 0.001
weight.data = weight.data - weight.grad * lr
weight.data

tensor([[-0.3310]])

In [10]:
weight.data

tensor([[-0.3310]])

In [11]:
## 업데이트된 파라미터로 추정 -> loss 계산
pred2 = X @ weight + bias
loss2 = torch.mean((pred2 - y)**2)

NameError: name 'X' is not defined

In [12]:
print(loss.item(), loss2.item())

NameError: name 'loss2' is not defined

In [ ]:
weight.data

### 모델링

In [ ]:
# 모델 정의
weight = torch.randn(1, 1, requires_grad=True)
bias =  torch.randn(1, requires_grad=True) 

# 추론 모델
def linear_model(X):
    return X @ weight + bias

In [24]:
# loss(오차) 계산 함수
def mse_loss_fn(pred, y):
    return torch.mean((pred-y)**2)

### 학습
1. 모델을 이용해 추정한다.
   - pred = model(input)
1. loss를 계산한다.
   - loss = loss_fn(pred, target)
1. 계산된 loss를 파라미터에 대해 미분하여 계산한 gradient 값을 각 파라미터에 저장한다.
   - loss.backward()
1. optimizer를 이용해 파라미터를 update한다.
   - optimizer.step()  
1. 파라미터의 gradient(미분값)을 0으로 초기화한다.
   - optimizer.zero_grad()
- 위의 단계를 반복한다.   

In [25]:
epochs = 2000 # train set을 몇 번 학습할지.
lr = 0.01
for epoch in range(epochs):
    #1. 추론(예측)
    pred = linear_model(X_train)
    # 2. 오차계산
    loss = mse_loss_fn(pred, y_train)
    # 3. 파라미터들(weight, bias)에 대한 gradient 계산
    loss.backward()
    # 4. 파라미터 업데이트
    weight.data = weight.data -lr * weight.grad
    bias.data = bias.data - lr * bias.grad
    # 5. gradient 초기화
    weight.grad = None
    bias.grad = None

    # 마지막 epoch, 100 epoch 마다 loss를 출력(성능개선 상황을 모니터링)
    if epoch % 100 == 0 or epoch == (epochs-1):
        print(f'[{epoch}/{epochs}] - loss: {loss.item():.4f}')



[0/2000] - loss: 1875.2142
[100/2000] - loss: 4.8689
[200/2000] - loss: 3.0087
[300/2000] - loss: 1.8592
[400/2000] - loss: 1.1489
[500/2000] - loss: 0.7099
[600/2000] - loss: 0.4387
[700/2000] - loss: 0.2711
[800/2000] - loss: 0.1675
[900/2000] - loss: 0.1035
[1000/2000] - loss: 0.0640
[1100/2000] - loss: 0.0395
[1200/2000] - loss: 0.0244
[1300/2000] - loss: 0.0151
[1400/2000] - loss: 0.0093
[1500/2000] - loss: 0.0058
[1600/2000] - loss: 0.0036
[1700/2000] - loss: 0.0022
[1800/2000] - loss: 0.0014
[1900/2000] - loss: 0.0008
[1999/2000] - loss: 0.0005


In [26]:
weight.data, bias.data

(tensor([[19.9735]]), tensor([0.0602]))

In [28]:
# 추론
with torch.no_grad():
    new_X = torch.tensor([[5],  [7]], dtype=torch.float32)
    pred =  linear_model(new_X)
    print(pred)

tensor([[ 99.9278],
        [139.8749]])


# 다중 입력, 다중 출력
- 다중입력: Feature가 여러개인 경우
- 다중출력: Output 결과가 여러개인 경우

다음 가상 데이터를 이용해 사과와 오렌지 수확량을 예측하는 선형회귀 모델을 정의한다.  
[참조](https://www.kaggle.com/code/aakashns/pytorch-basics-linear-regression-from-scratch)


|온도(F)|강수량(mm)|습도(%)|사과생산량(ton)|오렌지생산량|
|-|-|-|-:|-:|
|73|67|43|56|70|
|91|88|64|81|101|
|87|134|58|119|133|
|102|43|37|22|37|
|69|96|70|103|119|

```
사과수확량  = w11 * 온도 + w12 * 강수량 + w13 * 습도 + b1
오렌지수확량 = w21 * 온도 + w22 * 강수량 + w23 *습도 + b2
```

- `온도`, `강수량`, `습도` 값이 **사과**와, **오렌지 수확량**에 어느정도 영향을 주는지 가중치를 찾는다.
    - 모델은 사과의 수확량, 오렌지의 수확량 **두개의 예측결과를 출력**해야 한다.
    - 사과에 대해 예측하기 위한 weight 3개와 오렌지에 대해 예측하기 위한 weight 3개 이렇게 두 묶음, 총 6개의 weight를 정의하고 학습을 통해 가장 적당한 값을 찾는다.
        - `개별 과일를 예측하기 위한 weight들 @ feature들` 의 계산 결과를  **Node, Unit, Neuron** 이라고 한다.
        - 두 과일에 대한 Unit들을 묶어서 **Layer** 라고 한다.
- 목적은 우리가 수집한 train 데이터셋을 이용해 **정확한 예측을 위한 weight와 bias 들**을 찾는 것이다.

## Train Dataset
- Train data는 feature(input)와 target(output) 각각 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다. 이 문제에서는 `온도, 강수량, 습도` 세개의 변수를 가진다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 구성한다. 이 문제에서 예측할 항목은 `사과수확량, 오렌지 수확량` 2개의 값이다.

In [15]:
#  input: 생산환경 (temp, rainfall, humidity) : (5, 3)
environs = [
    [73, 67, 43], 
    [91, 88, 64], 
    [87, 134, 58], 
    [102, 43, 37], 
    [69, 96, 70]
]

# Targets: 생산량 - (apples, oranges) - (5, 2)
apple_orange_output = [
    [56, 70], 
    [81, 101], 
    [119, 133], 
    [22, 37], 
    [103, 119]
]

In [16]:
import torch
# Dataset을 torch.Tensor로 생성
X = torch.tensor(environs, dtype=torch.float32)
y = torch.tensor(apple_orange_output, dtype=torch.float32)
X.shape, y.shape

(torch.Size([5, 3]), torch.Size([5, 2]))

In [43]:
X

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

## weight와 bias
- weight: 각 feature들이 생산량에 영향을 주었는지의 가중치로 feature에 곱해줄 값.
    - 사과, 오렌지의 생산량을 구해야 하므로 가중치가 두개가 된다.
    - weight의 shape: `(3, 2)`
- bias는 모든 feature들이 0일때 생산량이 얼마일지를 나타내는 값으로 feature와 weight간의 가중합 결과에 더해줄 값이다.
    - 사과, 오렌지의 생산량을 구하므로 bias가 두개가 된다.
    - bias의 shape: `(2, )`

### Linear Regression model
모델은 weights `w`와 inputs `x`의 내적(dot product)한 값에 bias `b`를 더하는 함수.

$$
\hspace{2.5cm} X \hspace{1.1cm} \cdot \hspace{1.2cm} W \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\cdot
%
\left[ \begin{array}{cc}
w_{11} & w_{21} \\
w_{12} & w_{22} \\
w_{13} & w_{23}
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2} \\
b_{1} & b_{2} \\
\vdots & \vdots \\
b_{1} & b_{2} \\
\end{array} \right]
$$


$w_{11},\,w_{12},\,w_{13}$: 사과 생산량 계산시 각 feature들(생산환경)에 곱할 가중치   <br>
$w_{21},\,w_{22},\,w_{23}$: 오렌지 생산량 계산시 각 feature들(생산환경)에 곱할 가중치    

<center>
<img src="https://raw.githubusercontent.com/kgmyhGit/image_resource/main/deeplearning/figures/3_unit_layer.png">
</center>

In [ ]:
# weight/bias 를 정의 -> 초기값은 random 값을 이용해서 생성.
# 사과(3,1) 오랜지(3,1) => (3,2)
weight = torch.randn(3, 2, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

weight.size(), bias.size()
# weight: (3:input feature개수  ,  2:output 개수)
# bias  : (2:output 개수, )

(torch.Size([3, 2]), torch.Size([2]))

In [45]:
weight

tensor([[ 1.3852,  0.7991],
        [-0.0565, -1.4666],
        [ 0.5994, -2.9609]], requires_grad=True)

In [46]:
bias

tensor([-2.2074,  0.6727], requires_grad=True)

In [47]:
X

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [48]:
# 한번 학습(최적화)
## 추론
pred = X @ weight + bias

In [51]:
print(pred.size())
pred

torch.Size([5, 2])


tensor([[ 120.8963, -166.5709],
        [ 157.2295, -245.1635],
        [ 145.4914, -298.0587],
        [ 158.8270,  -90.4326],
        [ 129.8997, -292.2423]], grad_fn=<AddBackward0>)

In [52]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
## loss 계산(MSE)
loss = torch.mean((pred - y)**2) # 전체 추론한 결과의 평균오차를 계산.
# dim=0 이라서 생략, 1축의 각각 평균값을 구한다 ((((아주중요하다))))
loss

tensor(57713.5312, grad_fn=<MeanBackward0>)

In [54]:
# loss를 가지고 파라미터들(weight들, bias들)의 gradient 계산.
loss.backward()

In [55]:
weight.data

tensor([[ 1.3852,  0.7991],
        [-0.0565, -1.4666],
        [ 0.5994, -2.9609]])

In [56]:
weight.grad

tensor([[  5958.2988, -25529.3008],
        [  4614.4048, -29806.6719],
        [  3230.2610, -18166.0762]])

In [57]:
bias.data, bias.grad

(tensor([-2.2074,  0.6727]), tensor([  66.2688, -310.4936]))

In [58]:
# 파라미터 업데이트
lr = 0.00001
weight.data = weight.data - lr * weight.grad
bias.data = bias.data - lr * bias.grad

In [59]:
weight.data

tensor([[ 1.3256,  1.0544],
        [-0.1027, -1.1685],
        [ 0.5671, -2.7792]])

In [62]:
bias.data

tensor([-2.2080,  0.6758])

In [63]:
## 업데이트된 파라미터로 추정 -> loss 계산
pred2 = X @ weight + bias
loss2 = torch.mean((pred2 - y)**2)

In [64]:
print(loss.item(), loss2.item())

57713.53125 40069.62109375


##  모델링

In [65]:
weight = torch.randn(3, 2, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

## 모델 정의
def model(X):
    return X @ weight + bias

## loss 함수(MSE)
def loss_fn(pred, y):
    return torch.mean((pred - y)**2) # 전체 오차의 평균.

In [66]:
X.shape

torch.Size([5, 3])

In [67]:
epochs = 5000
lr = 0.00001  # 1e-5
for epoch in range(epochs):
    # 1. 추론
    pred = model(X)
    
    # 2. loss 계산
    loss = loss_fn(pred, y)
    # 3. 파라미터 들의 gradient 계산
    loss.backward()
    # 4. 파라미터 업데이트
    weight.data = weight.data - lr * weight.grad
    bias.data = bias.data - lr * bias.grad
    # 5. gradient 초기화
    weight.grad = None
    bias.grad = None
    ## 100 epoch, 마지막 epoch에서 loss를 출력 => 학습 과정 log를 출력
    if epoch % 100 == 0 or epoch == epochs-1:
        print(f"[{epoch+1:04d}/{epochs}] - {loss.item():.5f}")

[0001/5000] - 28658.15234
[0101/5000] - 478.17441
[0201/5000] - 268.72638
[0301/5000] - 187.09286
[0401/5000] - 145.22025
[0501/5000] - 117.73602
[0601/5000] - 96.97023
[0701/5000] - 80.31356
[0801/5000] - 66.65492
[0901/5000] - 55.36839
[1001/5000] - 46.01749
[1101/5000] - 38.26314
[1201/5000] - 31.83101
[1301/5000] - 26.49506
[1401/5000] - 22.06826
[1501/5000] - 18.39566
[1601/5000] - 15.34885
[1701/5000] - 12.82111
[1801/5000] - 10.72402
[1901/5000] - 8.98423
[2001/5000] - 7.54086
[2101/5000] - 6.34339
[2201/5000] - 5.34994
[2301/5000] - 4.52576
[2401/5000] - 3.84200
[2501/5000] - 3.27473
[2601/5000] - 2.80409
[2701/5000] - 2.41364
[2801/5000] - 2.08972
[2901/5000] - 1.82099
[3001/5000] - 1.59804
[3101/5000] - 1.41308
[3201/5000] - 1.25963
[3301/5000] - 1.13232
[3401/5000] - 1.02670
[3501/5000] - 0.93908
[3601/5000] - 0.86639
[3701/5000] - 0.80607
[3801/5000] - 0.75604
[3901/5000] - 0.71453
[4001/5000] - 0.68010
[4101/5000] - 0.65153
[4201/5000] - 0.62782
[4301/5000] - 0.60816
[4401

In [68]:
# 새로운 데이터로 추론
p = model(X)
p

tensor([[ 57.1557,  70.3218],
        [ 82.1155, 100.5501],
        [118.9158, 133.2111],
        [ 21.1457,  37.0862],
        [101.6980, 118.8856]], grad_fn=<AddBackward0>)

In [69]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [70]:
new_x = torch.tensor([68, 82, 56], dtype=torch.float32)     
new_x = new_x.unsqueeze(dim=0)      # 갯수는 없고 feature차원만 3개가 있다. # 차원을 늘려야함
new_x.shape

torch.Size([1, 3])

In [72]:
model(new_x)

tensor([[80.7039, 95.4518]], grad_fn=<AddBackward0>)

In [71]:
with torch.no_grad():
    p = model(new_x)
print(p)

tensor([[80.7039, 95.4518]])


# pytorch built-in 모델을 사용해 Linear Regression 구현

In [18]:
inputs = torch.tensor(
    [[73, 67, 43], 
     [91, 88, 64], 
     [87, 134, 58], 
     [102, 43, 37], 
     [69, 96, 70]], dtype=torch.float32)

In [19]:
targets = torch.tensor(
    [[56, 70], 
    [81, 101], 
    [119, 133], 
    [22, 37], 
    [103, 119]], dtype=torch.float32)

## torch.nn.Linear
Pytorch는 torch.nn.Linear 클래스를 통해 Linear Regression 모델을 제공한다.  
torch.nn.Linear에 입력 feature의 개수와 출력 값의 개수를 지정하면 random 값으로 초기화한 weight와 bias들을 생성해 모델을 구성한다.
- `torch.nn.Linear(input feature의 개수 , output 값의 개수)`

## Optimizer와 Loss 함수 정의
- **Optimizer**: 계산된 gradient값을 이용해 파라미터들을 업데이트 하는 함수
- **Loss 함수**: 정답과 모델이 예측한 값사이의 차이(오차)를 계산하는 함수.
  - 모델을 최적화하는 것은 이 함수의 값을 최소화하는 것을 말한다. 
- `torch.optim` 모듈에 다양한 Optimizer 클래스가 구현되있다.
- `torch.nn` 또는 `torch.nn.functional` 모듈에 다양한 Loss 함수가 제공된다. 

In [20]:
# 선형회귀 모델을 정의. torch.nn.Linear 클래스
import torch
import torch.nn as nn

model = nn.Linear(3, 2)  # 3: input feature 개수, 2: output 수

In [21]:
model.weight

Parameter containing:
tensor([[-0.5124,  0.2481, -0.4609],
        [-0.4701, -0.3148, -0.0482]], requires_grad=True)

In [22]:
model.bias

Parameter containing:
tensor([-0.4915, -0.2913], requires_grad=True)

In [23]:
# loss 함수
loss_fn = torch.nn.MSELoss()  # 클래스
# loss_fn = torch.nn.functional.mse_loss # 함수 

In [24]:
# optimizer (torch.optim 모듈에 정의): weight.data = weight.data - lr * weight.grad
optimizer = torch.optim.SGD(
    model.parameters(), # 최적화 대상 파라미터들을 model에서 조회해서 전달.
    lr = 0.00001,       # Learning Rate
)

In [25]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5124,  0.2481, -0.4609],
         [-0.4701, -0.3148, -0.0482]], requires_grad=True),
 Parameter containing:
 tensor([-0.4915, -0.2913], requires_grad=True)]

## Model Train

In [26]:
epochs = 5000

for epoch in range(epochs):
    # 추론
    pred = model(inputs)  
    # loss 계산
    loss = loss_fn(pred, targets) # torch.nn.functional.mse_loss(pred, targets) # (모델추정값, 정답)
    # gradient 계산
    loss.backward()

    # 파라미터 업데이트: optimizer.step()
    optimizer.step()        # w = w - lr * g

    # 파라미터 초기화 w.grad=None, b.grad=None
    optimizer.zero_grad()
    
    # 현재 epoch 학습 결과를 log로 출력
    if epoch % 100 == 0 or epoch == epochs-1:
        print(f"[{epoch+1:04d}/{epochs}] - {loss.item()}")

[0001/5000] - 22035.392578125
[0101/5000] - 86.82661437988281
[0201/5000] - 42.61507797241211
[0301/5000] - 27.161218643188477
[0401/5000] - 20.296295166015625
[0501/5000] - 16.272275924682617
[0601/5000] - 13.402826309204102
[0701/5000] - 11.153837203979492
[0801/5000] - 9.32496166229248
[0901/5000] - 7.8180365562438965
[1001/5000] - 6.570757865905762
[1101/5000] - 5.536813735961914
[1201/5000] - 4.679247856140137
[1301/5000] - 3.967844009399414
[1401/5000] - 3.3776824474334717
[1501/5000] - 2.888061046600342
[1601/5000] - 2.481865882873535
[1701/5000] - 2.144866466522217
[1801/5000] - 1.8652822971343994
[1901/5000] - 1.633338212966919
[2001/5000] - 1.440915584564209
[2101/5000] - 1.2812716960906982
[2201/5000] - 1.1488254070281982
[2301/5000] - 1.0389471054077148
[2401/5000] - 0.9477857351303101
[2501/5000] - 0.8721662759780884
[2601/5000] - 0.8094202280044556
[2701/5000] - 0.7573724985122681
[2801/5000] - 0.7141802906990051
[2901/5000] - 0.6783550977706909
[3001/5000] - 0.6486328840

In [27]:
# 추론 => gradient 계산을 할 필요가 없다. ==> grad_fn을 만들 필요가 없다. 그래서 torch.no_grad() 블록에서 추론 작업을 실행한다.
with torch.no_grad():
    pred = model(inputs)

In [28]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [29]:
pred

tensor([[ 57.0902,  70.2647],
        [ 82.2064, 100.6722],
        [118.8132, 133.0243],
        [ 21.1217,  37.0375],
        [101.8006, 119.0723]])

In [102]:
# 학습 로직을 함수 구현
def train(inputs, targets, epochs, model, loss_fn, optimizer):

    for epoch in range(epochs):
        # 추론
        pred = model(inputs)
        # loss 계산
        loss = loss_fn(pred, targets) # torch.nn.functional.mse_loss(pred, targets) # (모델추정값, 정답)
        # gradient 계산
        loss.backward()
        # 파라미터 업데이트: optimizer.step()
        optimizer.step()
        # 파라미터 초기화 w.grad=None, b.grad=None
        optimizer.zero_grad()
        # 현재 epoch 학습 결과를 log로 출력
        if epoch % 100 == 0 or epoch == epochs-1:
            print(f"[{epoch+1:04d}/{epochs}] - {loss.item()}")

In [103]:
model = nn.Linear(3, 2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

In [104]:
train(inputs, targets, 5000, model, nn.functional.mse_loss, optimizer)

[0001/5000] - 5952.8251953125
[0101/5000] - 12.488027572631836
[0201/5000] - 2.3456554412841797
[0301/5000] - 0.7915058732032776
[0401/5000] - 0.5533300638198853
[0501/5000] - 0.5168267488479614
[0601/5000] - 0.5112279057502747
[0701/5000] - 0.5103666186332703
[0801/5000] - 0.510233998298645
[0901/5000] - 0.5102073550224304
[1001/5000] - 0.5102006196975708
[1101/5000] - 0.5101960897445679
[1201/5000] - 0.5101892948150635
[1301/5000] - 0.5101851224899292
[1401/5000] - 0.5101823806762695
[1501/5000] - 0.5101789832115173
[1601/5000] - 0.510170578956604
[1701/5000] - 0.5101674199104309
[1801/5000] - 0.5101617574691772
[1901/5000] - 0.5101593732833862
[2001/5000] - 0.5101538300514221
[2101/5000] - 0.5101478099822998
[2201/5000] - 0.5101467370986938
[2301/5000] - 0.5101404786109924
[2401/5000] - 0.5101372003555298
[2501/5000] - 0.5101321935653687
[2601/5000] - 0.5101304054260254
[2701/5000] - 0.5101226568222046
[2801/5000] - 0.5101204514503479
[2901/5000] - 0.5101151466369629
[3001/5000] - 0